name: "GitHub CICD URL Extractor"
description: "Extract URLs from source code and ingest them into backend"

inputs:
  endpoint:
    description: "Backend ingestion endpoint"
    required: true
  organization_id:
    description: "Organization ID"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
